name: 'Docker build'
description: 'Build docker in workdir'
inputs:
  workdir:
    description: 'Build directory'
    required: true
    default: './'
  docker_name:
    description: 'Name of creation docker image'
    required: true
    default: ''
  builddir:
    description: 'Name of creation docker image'
    required: false
    default: '.'
  docker_login:
    description: 'Login to docker hub'
    required: true
    default: './'
  docker_password:
    description: 'Password to docker hub'
    required: true
    default: './'
runs:
  using: "composite"
  steps:
    - name: Generate Docker tags
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: |
          docker.io/vxcontrol/${{ inputs.docker_name }}
        tags: |
          type=ref,event=branch
          type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'master') }}
          type=semver,pattern={{version}}
        flavor: |
          latest=false

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ inputs.docker_login }}
        password: ${{ inputs.docker_password }}
    - name: Build and push
      uses: docker/build-push-action@v3
      env:
        DOCKER_BUILDKIT: 1
      with:
        push: true
        file: ${{ inputs.workdir }}/Dockerfile
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        context: ${{ inputs.builddir }}
