name: Build Agent OSX

on: workflow_call

jobs:
  agent_build_linux:
    name: Build agent OSX
    runs-on: ubuntu-latest
    container:
      image: vxcontrol/vxbuild-cross

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Common
        uses: ./.github/actions/common
      - name: Enable cache
        uses: ./.github/actions/go_cache
      - uses: actions/download-artifact@v3
        with:
          name: decode_environment
      - name: Build
        run: |
          cd build/package/agent/
          # darwin
          bash -x ./build-darwin-386.sh && mv -v ../../bin/vxagent  _tmp/darwin/386/
          bash -x ./build-darwin-amd64.sh && mv -v ../../bin/vxagent  _tmp/darwin/amd64/
          # Common components
          cp -v startup.sh _tmp/
          cp -v ../../artifacts/agent/version _tmp/

      - name: Upload result for agent OSX
        uses: actions/upload-artifact@v3
        with:
          name: agent_osx
          path: |
            build/package/*/_tmp/
