name: VXAgent installer build

on: workflow_call

jobs:
  build_installer_windows:
    name: Installer build
    environment:
      name: production
    runs-on: windows-2019

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/download-artifact@v3
        with:
          name: agent_windows
      - uses: actions/download-artifact@v3
        with:
          name: decode_environment
      - name: prepare files
        run: |
          mkdir build/package/agent/_tmp
          cp -r agent/_tmp/* build/package/agent/_tmp
          ls -R build/package/agent/_tmp
        shell: bash
      - name: Set path for heat.exe and light.exe
        run: echo "$WIX\\bin" >>$GITHUB_PATH
        shell: bash
      - name: Build Windows installer
        run: |
          cd build/package/agent
          pwsh -ExecutionPolicy Bypass -File build.ps1 packages.json vxagent
          mkdir install_windows
          cp dist/*.msi install_windows/

      - name: Upload result for msi installer
        uses: actions/upload-artifact@v3
        with:
          name: agent_msi
          path: |
            build/package/agent/install_windows/*.msi
