name: VXAgent installer build

on: workflow_call

jobs:
  build_installer_osx:
    name: Installer build
    environment:
      name: production
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/download-artifact@v3
        with:
          name: agent_osx
      - uses: actions/download-artifact@v3
        with:
          name: decode_environment
      - name: prepare files
        run: |
          mkdir build/package/agent/_tmp
          cp -r agent/_tmp/* build/package/agent/_tmp
          ls -R build/package/agent/_tmp
        shell: bash
      - name: Build macOS installer
        run: |
          cd build/package/agent
          chmod +x build-install-osx.sh
          VERSION=$(cat _tmp/version) ./build-install-osx.sh
          cp install_osx/vxagent-*_amd64.pkg _tmp/darwin/amd64/vxagent.pkg

      - name: Upload result for pkg installer
        uses: actions/upload-artifact@v3
        with:
          name: agent_pkg
          path: |
            build/package/agent/install_osx/*.pkg
