name: VXAgent installer build

on: workflow_call

jobs:
  build_installer_linux:
    name: Installer build
    environment:
      name: production
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/download-artifact@v3
        with:
          name: agent_linux
      - uses: actions/download-artifact@v3
        with:
          name: decode_environment
      - name: prepare files
        run: |
          mkdir build/package/agent/_tmp
          cp -r agent/_tmp/* build/package/agent/_tmp
          ls -R build/package/agent/_tmp
      - name: Build installer
        run: |
          cd build/package/agent
          chmod +x build-install-linux.sh
          ./build-install-linux.sh
      - name: Upload result for deb installer
        uses: actions/upload-artifact@v3
        with:
          name: agent_deb
          path: |
            build/package/agent/install_linux/*.deb
      - name: Upload result for rpm installer
        uses: actions/upload-artifact@v3
        with:
          name: agent_rpm
          path: |
            build/package/agent/install_linux/*.rpm
