name: VXServer build and push

on: workflow_call

jobs:
  build_and_push_docker:
    name: Docker Build and Publish
    environment:
      name: production
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/download-artifact@v3
        with:
          name: ui_backend
      - uses: actions/download-artifact@v3
        with:
          name: decode_environment
      - name: prepare_build
        run: |
          chmod +x build/bin/vxapi
      - name: Docker build vxapi
        uses: ./.github/actions/docker_build
        with:
          workdir: "build/package/api"
          docker_name: "soldr-api"
          docker_login: ${{ secrets.DOCKER_LOGIN }}
          docker_password: ${{ secrets.DOCKER_PASSWORD }}
